/**
 * Pre-rendered face-swap demos, one per book and per illustrated variant.
 *
 * Each frame pairs a real child's PHOTO with the cover art that photo produced
 * -- swapped by the production pipeline (Segmind faceswap-comic, at the
 * strengths in the API config) against the LIVE cover art, not a mock-up.
 * Showing the source photo beside the result is the point: a parent sees where
 * the face came from, which no amount of copy explains as well.
 *
 * GENERATED by tools/render_face_demos.py -- do not hand-edit; edit
 * tools/face-demos.json and re-run it with --emit-only. A book whose swaps
 * failed is absent here and falls back to its static cover, so this file is
 * also the record of which titles the demo actually covers.
 */
export type Gender = "boy" | "girl";

export type FaceDemoFrame = {
  /** The cover with this child's face swapped in. */
  src: string;
  /** The headshot that face came from, shown in the corner. */
  photo: string;
  /** The example child, named in the caption. */
  child: string;
};

export type FaceDemo = {
  /** The untouched illustration -- the "before" the loop returns to. */
  base: string;
  frames: FaceDemoFrame[];
  /** Where the face sits in the art, in % of the frame. Hand-checked: measuring
   *  it from the swap's own difference fails on covers where the model
   *  regenerates the background too. */
  face: { x: number; y: number; w: number; h: number };
};

const DEMOS: Record<string, Partial<Record<Gender, FaceDemo>>> = {
  "abc-adventure": {
    boy: {
      base: "/samples/faceswap/abc-adventure-boy-base.jpg",
      frames: [
        {
          src: "/samples/faceswap/abc-adventure-boy-a.jpg",
          photo: "/samples/faceswap/faces/boy-a.jpg",
          child: "Aarav",
        },
        {
          src: "/samples/faceswap/abc-adventure-boy-b.jpg",
          photo: "/samples/faceswap/faces/boy-b.jpg",
          child: "Vihaan",
        },
        {
          src: "/samples/faceswap/abc-adventure-boy-c.jpg",
          photo: "/samples/faceswap/faces/boy-c.jpg",
          child: "Kabir",
        },
      ],
      face: { x: 47, y: 42, w: 16, h: 18 },
    },
    girl: {
      base: "/samples/faceswap/abc-adventure-girl-base.jpg",
      frames: [
        {
          src: "/samples/faceswap/abc-adventure-girl-a.jpg",
          photo: "/samples/faceswap/faces/girl-a.jpg",
          child: "Anaya",
        },
        {
          src: "/samples/faceswap/abc-adventure-girl-b.jpg",
          photo: "/samples/faceswap/faces/girl-b.jpg",
          child: "Diya",
        },
        {
          src: "/samples/faceswap/abc-adventure-girl-c.jpg",
          photo: "/samples/faceswap/faces/girl-c.jpg",
          child: "Meera",
        },
      ],
      face: { x: 49, y: 44, w: 16, h: 18 },
    },
  },
  "baking-story": {
    girl: {
      base: "/samples/faceswap/baking-story-girl-base.jpg",
      frames: [
        {
          src: "/samples/faceswap/baking-story-girl-a.jpg",
          photo: "/samples/faceswap/faces/girl-a.jpg",
          child: "Anaya",
        },
        {
          src: "/samples/faceswap/baking-story-girl-b.jpg",
          photo: "/samples/faceswap/faces/girl-b.jpg",
          child: "Diya",
        },
        {
          src: "/samples/faceswap/baking-story-girl-c.jpg",
          photo: "/samples/faceswap/faces/girl-c.jpg",
          child: "Meera",
        },
      ],
      face: { x: 56, y: 52, w: 15, h: 18 },
    },
  },
  "beach-story": {
    boy: {
      base: "/samples/faceswap/beach-story-boy-base.jpg",
      frames: [
        {
          src: "/samples/faceswap/beach-story-boy-a.jpg",
          photo: "/samples/faceswap/faces/boy-a.jpg",
          child: "Aarav",
        },
        {
          src: "/samples/faceswap/beach-story-boy-b.jpg",
          photo: "/samples/faceswap/faces/boy-b.jpg",
          child: "Vihaan",
        },
        {
          src: "/samples/faceswap/beach-story-boy-c.jpg",
          photo: "/samples/faceswap/faces/boy-c.jpg",
          child: "Kabir",
        },
      ],
      face: { x: 66, y: 23, w: 15, h: 17 },
    },
    girl: {
      base: "/samples/faceswap/beach-story-girl-base.jpg",
      frames: [
        {
          src: "/samples/faceswap/beach-story-girl-a.jpg",
          photo: "/samples/faceswap/faces/girl-a.jpg",
          child: "Anaya",
        },
        {
          src: "/samples/faceswap/beach-story-girl-b.jpg",
          photo: "/samples/faceswap/faces/girl-b.jpg",
          child: "Diya",
        },
        {
          src: "/samples/faceswap/beach-story-girl-c.jpg",
          photo: "/samples/faceswap/faces/girl-c.jpg",
          child: "Meera",
        },
      ],
      face: { x: 75, y: 21, w: 15, h: 17 },
    },
  },
  "space-explorer": {
    boy: {
      base: "/samples/faceswap/space-explorer-boy-base.jpg",
      frames: [
        {
          src: "/samples/faceswap/space-explorer-boy-a.jpg",
          photo: "/samples/faceswap/faces/boy-a.jpg",
          child: "Aarav",
        },
        {
          src: "/samples/faceswap/space-explorer-boy-b.jpg",
          photo: "/samples/faceswap/faces/boy-b.jpg",
          child: "Vihaan",
        },
        {
          src: "/samples/faceswap/space-explorer-boy-c.jpg",
          photo: "/samples/faceswap/faces/boy-c.jpg",
          child: "Kabir",
        },
      ],
      face: { x: 43, y: 52, w: 27, h: 30 },
    },
  },
  "speed-racer": {
    boy: {
      base: "/samples/faceswap/speed-racer-boy-base.jpg",
      frames: [
        {
          src: "/samples/faceswap/speed-racer-boy-a.jpg",
          photo: "/samples/faceswap/faces/boy-a.jpg",
          child: "Aarav",
        },
        {
          src: "/samples/faceswap/speed-racer-boy-b.jpg",
          photo: "/samples/faceswap/faces/boy-b.jpg",
          child: "Vihaan",
        },
        {
          src: "/samples/faceswap/speed-racer-boy-c.jpg",
          photo: "/samples/faceswap/faces/boy-c.jpg",
          child: "Kabir",
        },
      ],
      face: { x: 64, y: 33, w: 15, h: 17 },
    },
  },
  "the-girl-and-the-magical-unicorn": {
    girl: {
      base: "/samples/faceswap/the-girl-and-the-magical-unicorn-girl-base.jpg",
      frames: [
        {
          src: "/samples/faceswap/the-girl-and-the-magical-unicorn-girl-a.jpg",
          photo: "/samples/faceswap/faces/girl-a.jpg",
          child: "Anaya",
        },
        {
          src: "/samples/faceswap/the-girl-and-the-magical-unicorn-girl-b.jpg",
          photo: "/samples/faceswap/faces/girl-b.jpg",
          child: "Diya",
        },
        {
          src: "/samples/faceswap/the-girl-and-the-magical-unicorn-girl-c.jpg",
          photo: "/samples/faceswap/faces/girl-c.jpg",
          child: "Meera",
        },
      ],
      face: { x: 36, y: 43, w: 15, h: 17 },
    },
  },
  "the-little-book-of-good-choices": {
    boy: {
      base: "/samples/faceswap/the-little-book-of-good-choices-boy-base.jpg",
      frames: [
        {
          src: "/samples/faceswap/the-little-book-of-good-choices-boy-a.jpg",
          photo: "/samples/faceswap/faces/boy-a.jpg",
          child: "Aarav",
        },
        {
          src: "/samples/faceswap/the-little-book-of-good-choices-boy-b.jpg",
          photo: "/samples/faceswap/faces/boy-b.jpg",
          child: "Vihaan",
        },
        {
          src: "/samples/faceswap/the-little-book-of-good-choices-boy-c.jpg",
          photo: "/samples/faceswap/faces/boy-c.jpg",
          child: "Kabir",
        },
      ],
      face: { x: 57, y: 38, w: 16, h: 18 },
    },
    girl: {
      base: "/samples/faceswap/the-little-book-of-good-choices-girl-base.jpg",
      frames: [
        {
          src: "/samples/faceswap/the-little-book-of-good-choices-girl-a.jpg",
          photo: "/samples/faceswap/faces/girl-a.jpg",
          child: "Anaya",
        },
        {
          src: "/samples/faceswap/the-little-book-of-good-choices-girl-b.jpg",
          photo: "/samples/faceswap/faces/girl-b.jpg",
          child: "Diya",
        },
        {
          src: "/samples/faceswap/the-little-book-of-good-choices-girl-c.jpg",
          photo: "/samples/faceswap/faces/girl-c.jpg",
          child: "Meera",
        },
      ],
      face: { x: 53, y: 39, w: 16, h: 18 },
    },
  },
};

/**
 * The demo for a book, or undefined where none was rendered.
 *
 * A both-gender book is illustrated twice and has a demo per variant; asking
 * for the variant that does not exist returns nothing rather than the other
 * one, because answering a visitor's Girl with a boy's cover is worse than
 * showing them the plain art.
 */
export function faceDemoFor(
  slug: string,
  gender: Gender = "boy",
): FaceDemo | undefined {
  return DEMOS[slug]?.[gender];
}
